services:
  web:
    build: .
    command: [ "make", "run" ]
    container_name: web
    env_file:
    - ".env"
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"
    restart: always
    networks:
      - web

  postgres:
    image: postgres:16.8-alpine
    container_name: postgres
    restart: always
    env_file: ".env"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5454:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - web

volumes:
  postgres-data:

networks:
  web:
    driver: bridge
    name: web
